#!/bin/sh

. /opt/etc/uhttpd.conf

ENABLED=yes
PROCS=uhttpd
ARGS="$OPTS"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
