#!/opt/bin/sh

#set -x

export PATH=$PATH

# Это временно. Переменную timezone должна определить ndms (прошивка)
timezone="$(ndmq -p "show clock date" -P tz/rule)"
export TZ="$timezone"

unset LD_BIND_NOW
unset LD_LIBRARY_PATH
unset LD_PRELOAD

# checking opkg timezone
if [ "$(ndmq -p "show running-config" -P message | grep "opkg timezone" | cut -d' ' -f1,2)" = "opkg timezone" ]
  then
	logger -t installer 'Info: Have you activated "opkg timezone" in CLI/web?'
	ndmq -p "opkg timezone $timezone"
fi

# checking opkg chroot
if [ "$(ndmq -p "show running-config" -P message | grep "opkg chroot")" = "opkg chroot" ]; then
	logger -t installer 'Info: Have you activated "opkg chroot" in CLI/web?'
#	logger -t installer 'Wow, OK!'
	for files in group passwd profile shell; do rm -f /opt/etc/$files; done
	for files in hosts resolv.conf; do cp /tmp/$files /opt/etc/; done
# checking opt fs
	check_fs_opt="$(mount | grep 'on / ' | cut -d' ' -f5)"
  else
	check_fs_opt="$(mount | grep 'on /opt ' | cut -d' ' -f5)"
fi

case "$check_fs_opt" in
    ext*)
	logger -t installer 'Info: Раздел пригоден для установки.'
    ;;
    *ntfs*)
	logger -t installer 'Info: Раздел NTFS! атрибуты "user:group" могут не поддерживаться.'
	logger -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3/ext4.'
    ;;
    *hfs*)
	logger -t installer 'Info: Раздел с HFS! (!не тестировалось!).'
	logger -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3/ext4.'
    ;;
    *)
        logger -t installer 'Critical error: Используйте накопитель с файловой системой ext2/ext3/ext4. Отменяем...'
	logger -t installer 'Выход из установки.'
	exit 1
    ;;
esac

# checking network
if ! ping -c 5 google.com > /dev/null 2>&1
  then
	logger -t installer 'Critical error: Ресурс недоступен. Проверьте настройки сети.'
	logger -t installer 'Выход из установки.'
	exit 1
  else
	logger -t installer 'Info: "ping google.com" ..... OK'
	sleep 1
fi

if ! ping -c 5 bin.entware.net > /dev/null 2>&1
  then
	logger -t installer 'Critical error: Ресурс недоступен. Повторите попытку позже.'
	logger -t installer 'Выход из установки.'
	exit 1
  else
	logger -t installer 'Info: "ping bin.entware.net" ..... OK'
	sleep 1
fi

logger -t installer '[1/5] Начало установки системы пакетов "Entware"...'

# This is for opkg only. The other folders will be created from opt-ndmsv2 package
# Только для opkg. Остальные каталоги будут созданы пакетом opt-ndmsv2
logger -t installer 'Info: Создание каталогов...'

for folder in lib/opkg tmp var/lock; do
	mkdir -p /opt/$folder
done

logger -t installer '[2/5] Загрузка и установка основных пакетов...'
if ! opkg update > /dev/null 2>&1
  then
	logger -t installer 'Critical error: Во время обновления списка пакетов произошла ошибка.'
	logger -t installer 'Выход из установки.'
	exit 1
fi

# install base packages
for ipk in libgcc libc libpthread librt entware-release findutils grep ldconfig locales ndmq opkg zoneinfo-asia zoneinfo-europe opt-ndmsv2 dropbear poorbox busybox; do
	logger -t installer "Info: Устанавливается пакет \"$ipk\"..."
  if ! opkg install $ipk > /dev/null 2>&1
    then
	logger -t installer "Critical error: Во время установки пакета \"$ipk\" произошла ошибка."
	logger -t installer 'Выход из установки.'
	exit 1
    else
	logger -t installer "Info: Пакет \"$ipk\" установлен."
	sleep 1
  fi
    if [ "$ipk" = "libc" ]; then
	dots.sh &
    fi
done

logger -t installer 'Info: Установка пакетов прошла успешно!'

dots-n.sh &
ldconfig > /dev/null 2>&1

# Установка прав для многопользовательской среды
# Fix for multiuser environment
chmod 777 /opt/tmp

# keygen
logger -t installer '[3/5] Генерация SSH-ключей...'

for key in rsa ecdsa; do
  rm /opt/etc/dropbear/dropbear_${key}_host_key
	logger -t installer "Info: Генерируется ключ \"$key\"..."
  if ! dropbearkey -t $key -f /opt/etc/dropbear/dropbear_${key}_host_key > /dev/null 2>&1
    then
	logger -t installer "Critical error: Во время генерации ключа \"$key\" произошла ошибка."
	logger -t installer 'Выход из установки.'
	exit 1
    else
	logger -t installer "Info: Ключ \"$key\" создан."
	sleep 1
  fi
done

logger -t installer '[4/5] Настройка сценария запуска, установка часового пояса и запуск "dropbear"...'

# TZ
timezone="$(ndmq -p "show clock date" -P tz/locality)"
ln -sf /opt/share/zoneinfo/"$timezone" /opt/etc/localtime

# SSH
if [ -f "/usr/sbin/dropbear" ] || [ -n "$(pidof dropbear)" ]; then
	sed -i 's,PORT=22,PORT=222,' /opt/etc/config/dropbear.conf
fi

/opt/etc/init.d/S51dropbear start

ndmq -p "opkg initrc /opt/etc/init.d/rc.unslung"
ndmq -p "system configuration save"

if grep -q "222" /opt/etc/config/dropbear.conf; then
	logger -t installer 'Можно открыть SSH-сессию для соединения с устройством (ssh root:keenetic@my.keenetic.net -p 222).'
  else
	logger -t installer 'Можно открыть SSH-сессию для соединения с устройством (ssh root:keenetic@my.keenetic.net).'
fi

logger -t installer '[5/5] Установка системы пакетов "Entware" завершена! Не забудьте сменить пароль и номер порта!'

rm "$0"
