#!/bin/sh

PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

CONF="/opt/etc/nginx/ext-ui.conf"

case $1 in
	start)
	nginx -c $CONF && echo 'Nginx ext-ui started.'
	;;
	stop)
	nginx -c $CONF -s quit && echo 'Nginx ext-ui gracefully stopped.'
	;;
	restart)
	nginx -c $CONF -s stop && nginx -c $CONF && echo 'Nginx ext-ui restarted.'
	;;
	reload)
	nginx -c $CONF -s reload && echo 'Nginx ext-ui configuration reload.'
	;;
	reopen)
	nginx -c $CONF -s reopen && echo 'Nginx ext-ui log files reopened.'
	;;
	test)
	nginx -c $CONF -t
	;;
	*)
	echo "Usage: $0 {start|stop|restart|reload|reopen|test}"
	;;
esac
