#!/bin/sh

# Please note it's not a system-wide settings, it's only for a current
# terminal session. Point your f\w (if necessery) to execute /opt/etc/profile
# at console logon.

export PATH='/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin:/usr/sbin:/usr/bin:/sbin:/bin'
export TERMINFO=/opt/share/terminfo
export TERM=xterm
export TMP=/opt/tmp
export TEMP=/opt/tmp
alias mc="mc -c"

# You may define localization
export LANG='ru_RU.UTF-8'
export LANGUAGE=''
export LC_CTYPE='ru_RU.UTF-8'
export LC_NUMERIC='ru_RU.UTF-8'
export LC_TIME='ru_RU.UTF-8'
export LC_COLLATE='ru_RU.UTF-8'
export LC_MONETARY='ru_RU.UTF-8'
export LC_MESSAGES='ru_RU.UTF-8'
export LC_PAPER='ru_RU.UTF-8'
export LC_NAME='ru_RU.UTF-8'
export LC_ADDRESS='ru_RU.UTF-8'
export LC_TELEPHONE='ru_RU.UTF-8'
export LC_MEASUREMENT='ru_RU.UTF-8'
export LC_IDENTIFICATION='ru_RU.UTF-8'
export LC_ALL=''

#export LANG='en_US.UTF-8'
#export LC_ALL='en_US.UTF-8'
